### ISSUE TITLE
name change

### ISSUE THREAD

**Issue by MicleBrick** [MicleBrick/ExplosionReversal#24]
looks like there's already an older (abandoned?) plugin with this name, hinders search results, only way to search this is to search it along with my name. a new name would be a good idea (wouldn't need to break anything, could automatically rename files etc). can't really think of a good one yet though

**Comment by BornToDoStuff** [comment]
Honestly just add something to the name that evokes the fact that its newer. That way people cant get confused if they see both when searching AND you can find the new one easier if you know its full name.
See for example Modern LWC, EssentialsX, and McMMO returns.

**Comment by MicleBrick** [comment]
Hmm... Not a bad idea. "ExplosionRegen9000" lol

**Comment by MicleBrick** [comment]
I've got it: ExplosionReversal. It captures the fact that this plugin is particularly thorough and pretty much completely reverses the explosions xD

**Comment by rsammelson** [comment]
That sounds like a good name
