### ISSUE TITLE
Regenerate blocks in logical order

### ISSUE THREAD

**Issue by ryantheleach** [MicleBrick/ExplosionReversal#41]
Sorting the list of blocks / entities to regen would help add to the aesthetic, as well as make it easier to not get stuck in holes.

Typically regening from the bottom up is preferred, and respawning entities last.

That said, if you wanted something better, then using a 'reverse flood fill' of connected non air non liquid blocks would be ideal, but difficult to implement.

**Comment by MicleBrick** [comment]
It already does this
